# src/program_default_values.py
#
# This file contains the default configuration settings for the application.
# It defines the structure and initial values for the config.ini file,
# ensuring that the application has a valid configuration to start with.
#
# Author: Anthony Peter Kuzub
# Blog: www.Like.audio (Contributor to this project)
#
# Professional services for customizing and tailoring this software to your specific
# application can be negotiated. There is no change to use, modify, or fork this software.
#
# Build Log: https://like.audio/category/software/spectrum-scanner/
# Source Code: https://github.com/APKaudio/
# Feature Requests can be emailed to i @ like . audio
#
#
# Version 20250813.001500.1

import os
from datetime import datetime

# Import the main frequency bands data
from ref.frequency_bands import SCAN_BAND_RANGES

# --- Version Information ---
current_version = "20250813.001500.1"
current_version_hash = (20250813 * 1500 * 1)

# --- Path Constants ---
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FOLDER_PATH = os.path.join(BASE_DIR, 'DATA')
CONFIG_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'config.ini')
PRESETS_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'presets.csv')
MARKERS_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'MARKERS.CSV')
VISA_COMMANDS_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'visa_commands.csv')
DEBUG_COMMANDS_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'DEBUG_SOFTWARE.log')


# --- Default Configuration Dictionary ---
DEFAULT_CONFIG = {
    'Application': {
        'geometry': '1000x1000+0+0',
        'window_state': 'normal',
        'paned_window_sash_position_percentage': '50',
        'last_config_save_time': 'Never',
    },
    'Debug': {
        'general_debug_enabled': 'False',
        'debug_to_gui_console': 'False',
        'debug_to_terminal': 'False',
        'debug_to_file': 'False',
        'include_console_messages_to_debug_file': 'False',
        'log_visa_commands_enabled': 'False',
    },
    'Instrument': {
        'visa_resource': '',
    },
    'InstrumentSettings': {
        'center_freq_mhz': '550.0',
        'span_freq_mhz': '100.0',
        'start_freq_mhz': '500.0',
        'stop_freq_mhz': '600.0',
        'rbw_mhz': '0.1',
        'vbw_mhz': '0.03',
        'vbw_auto_on': 'True',
        'initiate_continuous_on': 'True',
        'ref_level_dbm': '-30',
        'preamp_on': 'False',
        'power_attenuation_db': '10',
        'high_sensitivity_on': 'False',
        'trace1_mode': 'WRITE',
        'trace2_mode': 'MAXHOLD',
        'trace3_mode': 'BLANK',
        'trace4_mode': 'BLANK',
        'marker1_on': 'False',
        'marker2_on': 'False',
        'marker3_on': 'False',
        'marker4_on': 'False',
        'marker5_on': 'False',
        'marker6_on': 'False',
    },
    'MarkerTabDefaults': {
        'span': '1000000',
        'rbw': '1000000',
        'trace_live': 'True',
        'trace_max_hold': 'True',
        'trace_min_hold': 'True',
    },
    'Scan': {
        'output_folder': os.path.join(DATA_FOLDER_PATH, 'SCANS'),
        'scan_name': 'DefaultScan',
        'rbw_step_size_hz': '20000',
        'num_scan_cycles': '1',
        'cycle_wait_time_seconds': '0',
        'maxhold_enabled': 'False',
        'maxhold_time_seconds': '10',
        'desired_default_focus_width': '5000000',
        'create_html': 'True',
        'open_html_after_complete': 'True',
        'include_markers': 'True',
        'include_gov_markers': 'True',
        'include_tv_markers': 'True',
        'include_scan_intermod_markers': 'True',
        'math_average': 'True',
        'math_median': 'True',
        'math_variance': 'True',
        'math_standard_deviation': 'True',
        'math_range': 'True',
        'math_psd': 'True',
        'last_scan_configuration__selected_bands_levels': ','.join(
            [f"{band['Band Name']}=1" for band in SCAN_BAND_RANGES]
        ),
    },
    'Antenna': {
        'selected_antenna_type': 'Generic',
        'antenna_description': 'Broadband Omni',
        'antenna_use': 'General Purpose',
        'antenna_mount': 'Tripod',
        'antenna_amplifier': 'None',
    },
    'Amplifier': {
        'selected_amplifier_type': 'Generic',
        'amplifier_description': 'Inline LNA',
        'amplifier_use': 'Compensate for cable loss',
    },
    'Report': {
        'operator_name': 'RF Technician',
        'operator_contact': 'tech@example.com',
        'venue_name': 'Default Venue',
        'address_field': '123 Main St',
        'city': 'Anytown',
        'province': 'ON',
        'venue_postal_code': 'A1B 2C3',
        'notes': 'This is a default report generated by the OPEN-AIR software.',
        'freq_shift': '0.0',
        'scanner_type': 'Generic RF Scanner',
    },
    'Plotting': {
        'avg_include_tv_markers': 'True',
        'avg_include_gov_markers': 'True',
        'avg_include_markers': 'True',
        'avg_include_intermod_markers': 'True',
    }
}