# src/program_default_values.py
#
# This file contains the default configuration settings for the application.
# It defines the structure and initial values for the config.ini file,
# ensuring that the application has a valid configuration to start with.
#
# Author: Anthony Peter Kuzub
# Blog: www.Like.audio (Contributor to this project)
#
# Professional services for customizing and tailoring this software to your specific
# application can be negotiated. There is no change to use, modify, or fork this software.
#
# Build Log: https://like.audio/category/software/spectrum-scanner/
# Source Code: https://github.com/APKaudio/
# Feature Requests can be emailed to i @ like . audio
#
#
# Version 20250803.235000.0 (FIXED: Renamed 'address' key to 'address_field' to match UI variable.)
# Version 20250803.234500.0 (FIXED: Restored missing desired_default_focus_width key to Scan settings.)
# Version 20250803.233500.0 (ADDED: Default settings for the Markers Display Tab.)
# Version 20250803.235500.0 (ADDED: 'scanner_type' to Report section in DEFAULT_CONFIG.)
# Version 20250803.235900.0 (ADDED: avg_include_tv_markers, avg_include_gov_markers, avg_include_markers, avg_include_intermod_markers to Plotting section.)

current_version = "20250803.235900.0" # Incremented version

import os

# --- Path Constants ---
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FOLDER_PATH = os.path.join(BASE_DIR, 'DATA')
CONFIG_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'config.ini')
PRESETS_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'presets.csv')
MARKERS_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'MARKERS.CSV')
VISA_COMMANDS_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'DEBUG_VISA_COMMANDS.log')
DEBUG_COMMANDS_FILE_PATH = os.path.join(DATA_FOLDER_PATH, 'DEBUG_SOFTWARE.log')


# --- Default Configuration Dictionary ---
DEFAULT_CONFIG = {
    'Application': {
        'geometry': '1200x800+50+50',
        'paned_window_sash_position': '700',
        'last_config_save_time': 'Never',
    },
    'Debug': {
        'general_debug_enabled': 'True',
        'debug_to_gui_console': 'True',
        'debug_to_terminal': 'False',
        'debug_to_file': 'True',
        'include_console_messages_to_debug_file': 'True',
        'log_visa_commands_enabled': 'True',
    },
    'Instrument': {
        'visa_resource': 'TCPIP0::192.168.1.100::INSTR',
        'preamp_on': 'False',
        'reference_level_dbm': '-20.0',
        'high_sensitivity': 'False',
    },
    'MarkerTabDefaults': {
        'span': '1000000.0',
        'rbw': '1000000.0',
        'trace_live': 'True',
        'trace_max_hold': 'True',
        'trace_min_hold': 'True',
    },
    'Scan': {
        'output_folder': os.path.join(DATA_FOLDER_PATH, 'SCANS'),
        'scan_name': 'DefaultScan',
        'scan_mode': 'Standard',
        'scan_rbw_hz': '10000',
        'scan_rbw_segmentation': 'True',
        'rbw_step_size_hz': '20000',
        'num_scan_cycles': '1',
        'cycle_wait_time_seconds': '0',
        'maxhold_enabled': 'False',
        'maxhold_time_seconds': '10',
        'desired_default_focus_width': '5000000',
        'create_html': 'True',
        'open_html_after_complete': 'True',
        'include_markers': 'True',
        'include_gov_markers': 'True',
        'include_tv_markers': 'True',
        'include_scan_intermod_markers': 'True',
        'math_average': 'True',
        'math_median': 'True',
        'math_variance': 'True',
        'math_standard_deviation': 'True',
        'math_range': 'True',
        'math_psd': 'True',
    },
    'Antenna': {
        'selected_antenna_type': 'Generic',
        'antenna_description': 'Broadband Omni',
        'antenna_use': 'General Purpose',
        'antenna_mount': 'Tripod',
        'antenna_amplifier': 'None',
    },
    'Amplifier': {
        'selected_amplifier_type': 'Generic',
        'amplifier_description': 'Inline LNA',
        'amplifier_use': 'Compensate for cable loss',
    },
    'Report': {
        'operator_name': 'RF Technician',
        'operator_contact': 'tech@example.com',
        'venue_name': 'Default Venue',
        'address_field': '123 Main St',
        'city': 'Anytown',
        'province': 'ON',
        'venue_postal_code': 'A1B 2C3',
        'notes': 'This is a default report generated by the OPEN-AIR software.',
        'freq_shift': '0.0',
        'scanner_type': 'Generic RF Scanner',
    },
    'Plotting': { # NEW SECTION FOR PLOTTING SPECIFIC MARKER FLAGS
        'avg_include_tv_markers': 'True',
        'avg_include_gov_markers': 'True',
        'avg_include_markers': 'True',
        'avg_include_intermod_markers': 'True',
    }
}